plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.spotbugs' version '6.0.15'
    id 'pmd'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // env
    implementation 'io.github.cdimascio:dotenv-java:3.0.0'

    // jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // 소셜 로그인
    // 1. 구글
    implementation 'com.google.api-client:google-api-client:2.8.1'
    implementation("com.nimbusds:nimbus-jose-jwt:9.37.3")

    // 시큐리티
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // 데이터베이스
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.h2database:h2'

    // 프로메테우스
    implementation 'io.micrometer:micrometer-registry-prometheus'
    // 로키
    implementation 'com.github.loki4j:loki-logback-appender:2.0.3'
}

tasks.named('test') {
    useJUnitPlatform()
    systemProperty 'spring.profiles.active', 'test'
}

tasks.named('bootRun') {
    workingDir = projectDir
}

spotbugs {
    ignoreFailures = true
}

pmd {
    toolVersion = '7.8.0'
    ruleSets = [
            'category/java/bestpractices.xml',
            'category/java/errorprone.xml'
    ]
    ignoreFailures = true
}
