plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.spotbugs' version '6.0.15'
    id 'pmd'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    // env 설정
    developmentOnly 'me.paulschwarz:springboot4-dotenv:5.1.0'

    // 데이터베이스
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.h2database:h2'

    // 프로메테우스
    implementation 'io.micrometer:micrometer-registry-prometheus'
    // 로키
    implementation 'com.github.loki4j:loki-logback-appender:2.0.3'
}

tasks.named('test') {
    useJUnitPlatform()
}

spotbugs {
    ignoreFailures = true
}

pmd {
    toolVersion = '7.8.0'
    ruleSets = [
            'category/java/bestpractices.xml',
            'category/java/errorprone.xml'
    ]
    ignoreFailures = true
}
